### ISSUE TITLE
Incorrect logic when checking replica health

### ISSUE THREAD

**Issue by lawrencegripper** [containous/traefik-extra-service-fabric#18]
I picked this up while updating the tests. Don't this it is a serious issue as it could be impossible to achieve.

[The following line](https://github.com/containous/traefik-extra-service-fabric/blob/master/servicefabric.go#L306), I believe has the wrong logic. 

`(instanceData.ReplicaStatus == "Ready" || instanceData.HealthState != "Error")`

I think this should be:  

`(instanceData.ReplicaStatus == "Ready" && instanceData.HealthState != "Error")`

To handle a scenario where `ReplicaStatus: Down` and `HealthState: Warning`. As I say I'm unsure if this is possible in the cluster but happy to put in a PR to fix just in case. 

What do you think?

**Comment by ldez** [comment]
Yes open a PR on the branch v1.0 👍
