### ISSUE TITLE
Traefik version 1.6.0-rc2 seems to be using service fabric provider 1.1.1 and not 1.1.0

### ISSUE THREAD

**Issue by AviMualem** [containous/traefik-extra-service-fabric#25]
Recently i tried traefik version 1.6.0-rc2.
it looks like its supposed to use the 1.1.0 service fabric provider (according to the 1.6.0-rc1 release notes, issue can be fount at https://github.com/containous/traefik/pull/3064)

Im using custom template, and im basing it upon the default template in this repository.
as a starting point i took the template just like its in version 1.1.0 and bootstrap logs have the following message:

```
" level=error msg="Provider connection error: template: config.toml.tmpl:118: function \"getWhitelistSourceRange\" not defined; retrying in 687.177172ms""
```

when I'm working with custom template and just coping the template of the 1.1.1 version everything works okay.

In addition its clear to see that between 1.1.0 and 1.1.1 the `getWhitelistSourceRange` method was replaced with `getWhiteLis` (changes can be viewed at `servicefabric_config.go` file)

Currently its really hard to understand which sf provider version is actually integrated in a given traefik release.

I observed the Traefik repository and it seems like all the other providers source code is managed in the same repo as traefik. if the provider is separated its still vital to know which version of it is embedded to the current traefik release.

**Comment by ldez** [comment]
We will do that better the next time.
