### ISSUE TITLE
Support for multiple front-end rule sets

### ISSUE THREAD

**Issue by reddogaw** [containous/traefik-extra-service-fabric#37]
We require multiple front-end rule sets to be accessible for our Fabric Service. At the moment, it appears that additional `traefik.frontend.rule{.name}` labels will AND themselves together instead of OR.

My [StackOverflow question should detail our use-case](https://stackoverflow.com/questions/50885530/is-it-possible-to-have-multiple-traefik-front-ends-using-the-service-fabric-prov).

Another use case example would be to support multiple host names for our service.

**Suggested** label syntax could be something like this:

      <Extensions>
        <Extension Name="Traefik">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="traefik.frontends">local; external</Label> 
            <Label Key="traefik.frontend.local.rule">PathPrefixStrip: /my-service/</Label> 
            <Label Key="traefik.frontend.external.rule">Host: my-domain.localhost</Label> 
            <Label Key="traefik.frontends.passHostHeader">true</Label> 
            <Label Key="traefik.frontend.external.passHostHeader">false</Label> 
            <Label Key="traefik.enable">true</Label>
          </Labels>
        </Extension>
      </Extensions>

**Comment by ldez** [comment]
With Traefik, you can only combine multiple rules with an AND: https://docs.traefik.io/v1.6/basics/#combining-multiple-rules

https://github.com/containous/traefik/issues/3026

**Comment by reddogaw** [comment]
Yes, with Traefik rules will be AND-ed together for a single front-end. However, you can definitely define multiple front-ends which point at the same backend so that the rules for each front-end are OR-ed together.

This was intended as a feature request.

**Comment by ldez** [comment]
You can use a custom template if you want to automate this behavior:

```toml
[serviceFabric]

# Override default configuration template.
# For advanced users :)
#
# Optional
#
filename = "servicefabric.tmpl"
```
